package pl.uwb.cr2tt.model;

public enum ConversionMode {
    REIFIED_TRIPLE_EXPANDED,
    REIFIED_TRIPLE,
    REIFIED_TRIPLE_EXPLICIT,
    ANNOTATED_TRIPLE,
    ANNOTATED_TRIPLE_EXPLICIT,
    ANNOTATED_TRIPLE_EXPANDED,
    DIRECT_TRIPLE
}
